version: "3.5"

services:
  nextcloud:
    container_name: my_nextcloud
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nextcloud:/var/www/html
      - ./custom_apps/:/var/www/html/custom_apps
    ports:
      - "8080:80"
    privileged: true
  composer:
    container_name: my_phpunit
    build:
      context: .
      dockerfile: DockerfilePHPUnit
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ./docker/composer/volume:/app
      - ./custom_apps/:/app/custom_apps
  php:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
